// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grpc/internal/testgrpc/test.proto

package testgrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_grpc_internal_testgrpc_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_testgrpc_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_internal_testgrpc_test_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_grpc_internal_testgrpc_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_testgrpc_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_grpc_internal_testgrpc_test_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_internal_testgrpc_test_proto protoreflect.FileDescriptor

const file_grpc_internal_testgrpc_test_proto_rawDesc = "" +
	"\n" +
	"!grpc/internal/testgrpc/test.proto\x12\btestgrpc\"%\n" +
	"\vPingRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2@\n" +
	"\bPingPong\x124\n" +
	"\x04Ping\x12\x15.testgrpc.PingRequest\x1a\x13.testgrpc.PingReply\"\x00B/Z-github.com/circleci/ex/grpc/internal/testgrpcb\x06proto3"

var (
	file_grpc_internal_testgrpc_test_proto_rawDescOnce sync.Once
	file_grpc_internal_testgrpc_test_proto_rawDescData []byte
)

func file_grpc_internal_testgrpc_test_proto_rawDescGZIP() []byte {
	file_grpc_internal_testgrpc_test_proto_rawDescOnce.Do(func() {
		file_grpc_internal_testgrpc_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_internal_testgrpc_test_proto_rawDesc), len(file_grpc_internal_testgrpc_test_proto_rawDesc)))
	})
	return file_grpc_internal_testgrpc_test_proto_rawDescData
}

var file_grpc_internal_testgrpc_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_internal_testgrpc_test_proto_goTypes = []any{
	(*PingRequest)(nil), // 0: testgrpc.PingRequest
	(*PingReply)(nil),   // 1: testgrpc.PingReply
}
var file_grpc_internal_testgrpc_test_proto_depIdxs = []int32{
	0, // 0: testgrpc.PingPong.Ping:input_type -> testgrpc.PingRequest
	1, // 1: testgrpc.PingPong.Ping:output_type -> testgrpc.PingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_internal_testgrpc_test_proto_init() }
func file_grpc_internal_testgrpc_test_proto_init() {
	if File_grpc_internal_testgrpc_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_internal_testgrpc_test_proto_rawDesc), len(file_grpc_internal_testgrpc_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_internal_testgrpc_test_proto_goTypes,
		DependencyIndexes: file_grpc_internal_testgrpc_test_proto_depIdxs,
		MessageInfos:      file_grpc_internal_testgrpc_test_proto_msgTypes,
	}.Build()
	File_grpc_internal_testgrpc_test_proto = out.File
	file_grpc_internal_testgrpc_test_proto_goTypes = nil
	file_grpc_internal_testgrpc_test_proto_depIdxs = nil
}
