version: "3.7"

services:
  postgres:
    image: circleci/postgres:13.5-ram
    ports:
      - '127.0.0.1:5432:5432'
    shm_size: '512mb'
    command: postgres -c shared_buffers=512MB -c max_connections=400
    environment:
      PGUSER: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  mongo:
    image: mongo:8.2
    ports:
      - '127.0.0.1:27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dbname

  redis:
    image: cimg/redis:8.6
    command: [
      "redis-server",
      "--protected-mode", "no",
      "--databases", "1000000",
    ]
    ports:
      - '127.0.0.1:6379:6379'

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    shm_size: '512mb'
    volumes:
      - /dev/shm:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  statsd:
    image: catkins/statsd-logger
    ports:
      - '127.0.0.1:8125:8125/udp'

  seaweedfs:
    image: chrislusf/seaweedfs
    command: ['server', '-s3', '-s3.port=9123', '-s3.config=/etc/seaweedfs/s3config.json']
    volumes:
      - ./testing/s3fixture/s3config.json:/etc/seaweedfs/s3config.json
    ports:
      - '127.0.0.1:9123:9123'

  vault:
    image: hashicorp/vault:1.21.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dummyroot
    ports:
      - '127.0.0.1:8200:8200'
      - '127.0.0.1:8201:8201'
    cap_add:
      - IPC_LOCK

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
      LOG_LEVEL: debug
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
